---
- name: Copy cluster config template
  template:
    src: "{{ role_path }}/templates/cluster-config.yaml.j2"
    dest: "/tmp/cluster-config.yaml"
    mode: 0644
  tags:
    - create

- name: Create kind cluster
  shell: "kind create cluster --name {{ cluster_name }} --config /tmp/cluster-config.yaml"
  tags:
    - create

- name: Cluster creation has been finished
  debug:
    msg: "Cluster creation of kind cluster {{ cluster_name }} has been finished."
  tags:
    - create

- name: plouf
  setup:
    gather_subset: env
  tags:
    - create

- name: env value
  debug:
    msg: "Home {{ ansible_env.HOME }} or {{ lookup('env', 'HOME') }}"
  tags:
    - create

- name: Create .kube directory
  file:
    mode: "0755"
    ##path: "{{ ansible_env.HOME }}/.kube"
    path: "/{{ lookup('env', 'HOME') }}/.kube"
    state: directory
  tags:
    - create

- name: Generate kubeconfig file
  shell: "kind get kubeconfig > /{{ lookup('env', 'HOME') }}/.kube/config"
  register: kubeconfig_output
  tags:
    - create
## - name: Save kubeconfig to file
##  copy:
##    content: "{{ kubeconfig_output.stdout }}"
##    dest: "/root/.kube/config"
##dest: " {{ ansible_env.HOME }}/.kube/config"
##    mode: "0600"
##  tags:
##   - create
